#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"
LOGERR="$GAMEDIR/patch_error.txt"

# Redirect output and error to the log file
rm -rf $LOGFILE $LOGERR
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Exports
export DATADIR="$GAMEDIR/assets"
export DATAFILE="picayune.port"
export LD_LIBRARY_PATH="/usr/lib:$GAMEDIR/lib:$GAMEDIR/tools/libs:$LD_LIBRARY_PATH"
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
export TOOLDIR="$GAMEDIR/tools"
export TMPDIR="$GAMEDIR/tmp"
export PATH="$GAMEDIR/tools:$PATH"

# Permissions
chmod 666 /dev/uinput
chmod 777 "$TOOLDIR/gmKtool.py"
chmod 777 "$TOOLDIR/oggenc"

cd "$GAMEDIR"

initial_setup() {
    rm -f "$DATADIR"/*.exe "$DATADIR"/*.dll "$DATADIR"/*.meow "$DATADIR/.gitkeep"
    [ -f "$DATADIR/splash.png" ] && mv "$DATADIR/splash.png" .
    echo "Removed unnecessary files"
    sleep 1
}

unzip_patch() {
    echo "Unzipping the patch file..."
    if [ -f "./tools/patches/picayune.zip.001" ]; then
        if [ -x "$(command -v 7z)" ]; then
            ./tools/7za x ./tools/patches/picayune.zip.001 -o./tools/patches
            if [ $? -eq 0 ]; then
                echo "Patch file successfully extracted."
                rm ./tools/patches/picayune.zip.*
                rm "$TOOLDIR/7za"
            else
                echo "Failed to extract multi-part archive."
                exit 1
            fi
        else
            echo "7za tool is not available. Failed to extract xdelta patch."
            exit 1
        fi
    else
        echo "Patch archive not found! Maybe it's already unzipped?"
    fi
}

apply_xdelta() {
    echo "Applying xdelta patch"
    # Check if the data.win file exists and apply xdelta
    if [ -f "$DATADIR/data.win" ] && [ -f "$TOOLDIR/patches/picayune.xdelta" ]; then
        output=$(xdelta3 -d -s "$DATADIR/data.win" -f "$TOOLDIR/patches/picayune.xdelta" "$DATADIR/game.droid" 2>&1)
        if [ $? -eq 0 ]; then
            echo "Patch applied successfully"
            echo "$output"
            rm "$DATADIR/data.win" && rm "$TOOLDIR/patches/picayune.xdelta"
            sleep 1
        else
            echo "Failed to apply patch"
            echo "$output"
            mv $LOGFILE $LOGERR
            sleep 1
            exit 1
        fi
    else
        echo "No data.win file found to patch or no patch file provided."
        mv "$DATADIR/data.win" "$DATADIR/game.droid"
        sleep 1
    fi
}

compress_audio() {
    mkdir -p "$TMPDIR"

    # Run the compression tool
    PYTHON=$(which python3)
    echo "Running GMTools on data and audiogroups."
    $PYTHON ./tools/gmKtool.py -vv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"

    if [ $? -eq 0 ]; then
        echo "Compression completed successfully."
        mv "$TMPDIR/"* "$DATADIR"
        echo "Moved compressed files to $DATADIR."
        rm -rf "$TMPDIR"
        echo "Temporary directory $TMPDIR removed."
        echo "Audio compression applied successfully."
    else
        echo "Audio compression failed."
        echo "Cleaning up temporary directory $TMPDIR."
        rm -rf "$TMPDIR"
    fi
}

zip_archive() {
        echo "Finishing up..."
        zip -r -0 $DATAFILE ./assets/
        mkdir -p saves
        rm -rf $DATADIR/*
        sleep 1
}

process_game() {
    initial_setup
    #unzip_patch
    apply_xdelta
    compress_audio
    zip_archive
	
    # Final completion message
    echo "Patching process complete!"
}

process_game
